export type MarketplaceMainCategory =
  | 'Jewelry'
  | 'Home & Living'
  | 'Bath & Beauty'
  | 'Clothing & Accessories'
  | 'Fine Art & Collectibles'
  | 'Fun & Games'
  | 'Wedding & Celebrations'
  | 'Handmade Supplies'
  | 'Tools & Equipment'
  | 'Holiday & Seasonal'

export interface MarketplaceCategoryGroup {
  main: MarketplaceMainCategory
  subcategories: string[]
}

export const goimagineCategories: MarketplaceCategoryGroup[] = [
  {
    main: 'Jewelry',
    subcategories: [
      'Necklaces',
      'Beaded Necklaces',
      'Pendant Necklaces',
      'Chokers',
      'Charm Necklaces',
      'Statement Necklaces',
      'Monogram & Name Necklaces',
      'Chains',
      'Lockets',
      'Rings',
      'Stackable Rings',
      'Statement Rings',
      'Midi Rings',
      'Multi-Stone Rings',
      'Wedding Bands',
      'Engagement Rings',
      'Promise Rings',
      'Signet Rings',
      'Bridal Sets',
      'Earrings',
      'Dangle & Drop Earrings',
      'Stud Earrings',
      'Hoop Earrings',
      'Cuff & Wrap Earrings',
      'Gauge & Plug Earrings',
      'Jacket & Crawler Earrings',
      'Clip-on Earrings',
      'Chandelier Earrings',
      'Threader Earrings',
      'Bracelets',
      'Beaded Bracelets',
      'Bangles',
      'Cuff Bracelets',
      'Charm Bracelets',
      'Chain & Link Bracelets',
      'Woven & Braided Bracelets',
      'ID & Medical Bracelets',
      'Wrap Bracelets',
      'Pins & Brooches',
      'Enamel Pins',
      'Novelty Pins',
      'Brooches',
      'Body Jewelry',
      'Anklets',
      'Arm Cuffs',
      'Nose Rings',
      'Lip Rings',
      'Belly Rings & Chains',
      'Toe Rings',
      'Barbells',
      'Body Chains',
      'Shoulder Jewelry',
      'Barefoot Sandals',
      'Jewelry Accessories',
      'Cuff Links & Tie Clips',
      'Jewelry Storage',
      'Ring Trees',
      'Ring Dishes',
      'Earring Storage',
      'Necklace Storage',
      'Jewelry Boxes',
      'Jewelry Bags',
      'Charms & Pendants',
      'Charms',
      'Pendants',
      'Watches',
      'Wrist Watches',
      'Watch Bands',
      'Pocket Watches',
      'Jewelry Sets',
      'Cremation & Memorial Jewelry',
    ],
  },
  {
    main: 'Home & Living',
    subcategories: [
      'Home Decor',
      'Ornaments',
      'Pillows & Cushions',
      'Wreath & Door Hangings',
      'Floral & Indoor Planters',
      'Vases, Jars & Ceramics',
      'Decorative Trays',
      'Clocks',
      'Decorative Accessories',
      'Book Ends',
      'Piggy Banks',
      'Curtains & Window Treatments',
      'Rugs & Door Mats',
      'Bathroom Decor',
      'Signs',
      'Wood Signs',
      'Metal Signs',
      'Address Signs',
      'Marquee & Letterboard',
      'Vinyl Signs',
      'Kitchen & Dining',
      'Drinkware',
      'Mugs',
      'Traditional Pottery Mugs',
      'Hand Painted Mugs',
      'Graphic Mugs',
      'Personalized Mugs',
      'Travel Mugs',
      'Tumblers & Water Bottles',
      'Barware',
      'Stem Glasses',
      'Bottle Openers',
      'Bottle Stoppers',
      'Drink Flights',
      'Shot Glasses',
      'Steins',
      'Flasks',
      'Drink Accessories',
      'Coasters',
      'Drink Cozies',
      'Drink Charms',
      'Drink Labels',
      'Tableware',
      'Bowls',
      'Wooden Bowls',
      'Pottery Bowls',
      'Other Bowls',
      'Plates',
      'Cutlery & Knives',
      'Chopsticks',
      'Cookware & Baking',
      'Cooking Utensils',
      'Tongs',
      'Ladles',
      'Spatulas',
      'Mixing Spoons',
      'Measuring Spoons',
      'Measuring Cups',
      'Rolling Pins',
      'Cookie Cutters',
      'Pie Plates',
      'Casserole Dishes',
      'Mixing Bowls',
      'Pizza Stones & Paddles',
      'Trays & Platters',
      'Trays',
      'Platters',
      'Charcuterie Boards',
      'Cheese Boards',
      'Cutting Boards',
      'Sectioned Trays',
      'Lazy Susans',
      'Serveware',
      'Salt & Pepper Shakers',
      'Serving Utensils',
      'Cake Stands',
      'Large Bowls',
      'Gravy Boats',
      'Pitchers & Carafes',
      'Teapots',
      'Linens',
      'Kitchen Linens',
      'Dishcloths & Towels',
      'Tea Towels',
      'Kitchen Aprons',
      'Pot Holders',
      'Drying Mats',
      'Bowl Cozies',
      'Table Linens',
      'Napkins',
      'Placemats',
      'Tablecloths',
      'Table Runners',
      'Magnets',
      'Kitchen Decor',
      'Kitchen Storage',
      'Jars & Canisters',
      'Utensil Holders',
      'Recipe Boxes & Stands',
      'Spice Racks & Storage',
      'Pot Racks',
      'Knife Blocks',
      'Napkin Holders',
      'Towel Racks',
      'Beer Caddies',
      'Wine Racks',
      'Food Storage',
      'Food Wrappers',
      'Snack Bags',
      'Lunch Boxes & Bags',
      'Bowl Covers',
      'Food Containers',
      'Kitchen Accessories',
      'Spoon Rests',
      'Trivets',
      'Wall Decor',
      'Wall Hangings',
      'Wall Decals',
      'Frames',
      'Wall Art',
      'Framed Art',
      'Canvas Prints',
      'Wooden Prints',
      'Metal Prints',
      'Posters',
      'Shelving & Ledges',
      'Mirrors',
      'Wallpaper',
      'Peel & Stick',
      'Traditional Wall Paper',
      'Wall Stencils',
      'Tapestries',
      'Baby & Kids',
      'Kids Bedding',
      'Crib Bedding',
      'Moses Baskets & Nests',
      'Feeding',
      'Play Mats',
      'Nursery Decor',
      'Playroom Decor',
      'Bibs & Burp Cloths',
      'Pacifier Clips & Teething',
      'Pets',
      'Pet Clothing & Accessories',
      'Pet Bandanas',
      'Pet Bows & Hair Accessories',
      'Pet ID Tags',
      'Pet Diapers',
      'Pet Totes',
      'Collars & Leashes',
      'Pet Bag Holders',
      'Pet Toys',
      'Pet Feeding',
      'Feeding Stands',
      'Pet Bowls',
      'Pet Mats',
      'Pet Treats',
      'Pet Carriers',
      'Pet Gates & Fences',
      'Pet Storage',
      'Pet Bedding',
      'Pet Grooming',
      'Horse Tack',
      'Taxidermy',
      'Animal Mounts',
      'Insects',
      'Faux Taxidermy',
      'Bedroom',
      'Sheets & Pillowcases',
      'Duvet Covers',
      'Blankets & Throws',
      'Bedroom Pillows',
      'Bedroom Decor',
      'Outdoor & Garden',
      'Outdoor Planters & Pots',
      'Plant Hangers',
      'Plant Markers',
      'Garden Decorations',
      'Wind Chimes',
      'Sun Catchers',
      'Garden Gloves & Aprons',
      'Garden Gloves',
      'Garden Aprons',
      'Plant Stands',
      'Bird Houses & Feeders',
      'Patio',
      'House Numbers',
      'Mailboxes',
      'Flags',
      'Seed Bombs',
      'Barn Quilts',
      'Furniture',
      'Kids Furniture',
      'Living Room Furniture',
      'Bedroom Furniture',
      'Entryway Furniture',
      'Office Furniture',
      'Steps & Stools',
      'Furniture Cushions & Covers',
      'Knobs & Pulls',
      'Office & Organization',
      'Office & School Supplies',
      'Desk Storage',
      'Desk Accessories',
      'Nameplates',
      'Desk Card Holders',
      'Paperweights',
      'Tech Accessories',
      'Bulletin Boards',
      'Boxes & Bins',
      'Calendars & Planners',
      'Notepads',
      'Notebooks & Journals',
      'Junk Journals',
      'Pens, Pencils & Writing',
      'Schooling Supplies',
      'Finance & Budgeting',
      'Decals & Stickers',
      'Vinyl Decals',
      'Stickers',
      'Sticker Sheets',
      'Sticker Books',
      'Planner Stickers',
      'Candles',
      'Candle Holders',
      'Wax Melts',
      'Incense & Holders',
      'Room Spray',
      'Blankets & Quilts',
      'Quilts',
      'Fleece Blankets',
      'Knit & Crochet Blankets',
      'Throws',
      'Seasonal Decor',
      'Easter Baskets',
      'Spring Decor',
      'Patriotic Decor',
      'Holiday Decor',
      'Ornaments',
      'Stockings',
      'Christmas Trees',
      'Tree Skirts',
      'Tree Toppers',
      'Angels',
      'Cleaning & Laundry',
      'Hampers & Bags',
      'Cleaning Supplies',
      'Laundry Supplies',
      'Storage & Organization',
      'Baskets',
      'Boxes & Bins',
      'Trinket Bowls',
      'Diaper Caddies',
      'Hooks & Hangers',
      'Recycling & Trash',
      'Outdoor Storage',
      'Toy Storage',
      'Closet Organization',
      'Storage Labels',
      'Religious & Spirituality',
      'Prayer Beads',
      'Lucky Charms & Amulets',
      'Crystals',
      'Religious & Sacred Home Decor',
      'Ketubah',
      'Candles, Incense & Oils',
      'Reiki & Chakras',
      'Tarot',
      'Meditation',
      'Religious Studies',
      'Religious & Spiritual Clothing',
      'Prayer Shawls',
      'Vestments',
      'Head Coverings',
      'Memorials & Loss',
      'Grave Markers',
      'Urns',
      'Altars, Shrines & Tools',
      'Garage & Auto',
      'Car Accessories',
      'Car Air Fresheners',
      'Car Coasters',
      'Seat Covers',
      'Steering Wheel Covers',
      'License Plate Frames',
      'Car Decor',
      'Garage Storage',
      'Electronics Accessories',
      'Headphone Stands',
      'Cord Ties & Organizers',
      'Phone & Tablet Holders',
      'Phone Accessories',
      'Phone Cases',
      'Phone Charms',
      'Laptop Accessories',
      'Laptop Bags',
      'Laptop Sleeves',
      'Tablet & E-reader Sleeves',
      'Camera Bags & Cases',
      'Video Game Accessories',
      'Video Game Cases',
      'Video Game Storage',
      'Lighting',
      'Hanging Lights',
      'Floor Lamps',
      'Table Lamps',
      'Task Lights',
      'Night Lights',
      'Lamp Shades',
      'Wellness Accessories',
      'Tube & Port Accessories',
      'Wheelchair Accessories',
      'Mobility Accessories',
      'Canes',
      'Walker Accessories',
      'Adaptive Clothing',
      'Baby Adaptive Clothing',
      'Kids Adaptive Clothing',
      'Adult Adaptive Clothing',
      'Post Surgery Accessories',
      'Ostomy & Catheter Bag Covers',
      'Independent Living Aids',
      'Health Organizers',
      'Medical Device Bags',
      'Scrub Wear',
      'Scrub Hats',
      'Menstrual Care',
      'Incontinence Care',
      'Food & Beverage',
      'Beverages',
      'Coffee',
      'Hot Chocolate',
      'Juice',
      'Carbonated Beverages',
      'Drink Mixes',
      'Candied Spoons',
      'Tea',
      'Baked Goods',
      'Bagels',
      'Baking Mixes',
      'Biscotti',
      'Bread',
      'Brownies',
      'Cake & Cupcakes',
      'Cookies',
      'Donuts',
      'Macarons',
      'Pastries',
      'Pies',
      'Candy',
      'Bark & Brittles',
      'Caramels',
      'Chocolates',
      'Fudge',
      'Gummy Candy',
      'Hard Candy',
      'Lollipops',
      'Marshmallows',
      'Toffee',
      'Truffles',
      'Snacks',
      'Popcorn',
      'Pretzels',
      'Chips',
      'Crackers',
      'Granola',
      'Nuts & Seeds',
      'Spices & Herbs',
      'Spice Mixes',
      'Rubs',
      'Extracts',
      'Soup Mixes',
      'Condiments & Sauces',
      'Dressings',
      'Mustard',
      'Ketchup',
      'Cooking Sauce',
      'Marinades',
      'Oils',
      'Salsa & Dip',
      'Syrups',
      'Honey',
      'Preserves',
      'Chutneys',
      'Jams & Jellies',
      'Fruit Butter',
      'Marmalades',
      'Grains',
      'Pasta',
      'Cereal & Oats',
      'Rice',
      'Dried Foods',
      'Dried Fruits',
      'Dried Vegetables',
      'Jerky',
      'Smoked Meat',
      'Pickles',
    ],
  },
  {
    main: 'Bath & Beauty',
    subcategories: [
      'Soaps & Washes',
      'Soaps',
      'Body Wash',
      'Bath Bombs',
      'Bath Salts & Scrubs',
      'Bath Oils',
      'Bubble Bath & Soaks',
      'Skin Care',
      'Facial Care',
      'Moisturizers',
      'Balms & Salves',
      'Exfoliation',
      'Eye Treatments',
      'Spa & Relaxation',
      'Aromatherapy',
      'Heat & Cold Packs',
      'Massage',
      'Essential Oils',
      'Robes',
      'Spa Kits',
      'Personal Care',
      'Shaving & Grooming',
      'Aftershave',
      'Shaving Creams',
      'Beard & Mustache',
      'Razors',
      'Shaving Kits',
      'Waxing',
      'Hand Sanitizers',
      'Deodorant',
      'Bug Repellent',
      'Oral Care',
      'Menstrual Care',
      'Face Masks',
      'Pill Boxes & Medicine Caddies',
      'Cosmetics',
      'Eyes',
      'Eye Shadow',
      'Primers',
      'Eyebrow Care',
      'Mascara',
      'Eyeliners',
      'Lips',
      'Lip Color',
      'Lip Balms',
      'Lip Gloss',
      'Lip Scrubs',
      'Face',
      'Blush & Cheek',
      'Powder',
      'Foundation',
      'Concealers & Primers',
      'Face & Body Paint',
      'Nails & Nail Care',
      'Nail Polish',
      'Acrylic & Press On Nails',
      'Nail Stamping',
      'Nail Stencils',
      'Nail Decals & Wraps',
      'Nail Treatments',
      'Nail Files & Tools',
      'Makeup Tools & Brushes',
      'Reusable Wipes',
      'Hand Mirrors',
      'Makeup Remover',
      'Makeup Brushes',
      'Cosmetic Bags',
      'Hair Care',
      'Shampoos',
      'Conditioners & Treatments',
      'Brushes & Combs',
      'Waxes & Gels',
      'Hair Dye & Color',
      'Shower Caps',
      'Hair Extensions',
      'Wigs',
      'Baby & Child Care',
      'Nursing',
      'Diapers & Changing Pads',
      'Wet Bags',
      'Baby Shampoo & Bath',
      'Bath Accessories',
      'Bath Accessories & Caddies',
      'Toiletry Bags',
      'Washcloths & Towels',
      'Sponges & Body Brushes',
      'Loofahs & Poufs',
      'Scrubbers & Wipes',
      'Soap Dishes & Dispensers',
      'Bathroom Storage & Organizers',
      'Fragrances',
    ],
  },
  {
    main: 'Clothing & Accessories',
    subcategories: [
      "Women's Shirts & Tops",
      'Tank Tops',
      'Shirts & Blouses',
      'Tunics',
      'Graphic Tees',
      'Sweatshirts & Hoodies',
      'Skirts',
      'Dresses',
      'Pants',
      'Shorts',
      'Outerwear',
      'Jackets & Coats',
      'Sweaters',
      'Vests',
      'Pajamas & Loungewear',
      'Robes & Kimonos',
      'Activewear',
      'Swimwear',
      'One Piece',
      'Two Piece',
      'Coverups',
      'Undergarments',
      'Bras',
      'Underwear',
      'Maternity Tops',
      'Maternity Bottoms',
      'Maternity Dresses',
      'Maternity Active & Loungewear',
      'Maternity Nursing',
      "Men's Shirts",
      'Men’s Graphic Tees',
      'Sweaters',
      'Sweatshirts & Hoodies',
      'Activewear',
      'Outerwear Jackets & Coats',
      'Vests',
      'Pants',
      'Shorts',
      'Pajamas & Robes',
      'Suits',
      'Swimwear',
      'Undergarments',
      'Unisex Clothing',
      'Tops',
      'Graphic Tees',
      'Sweatshirts & Hoodies',
      'Tank Tops',
      'Shirts',
      'Bottoms',
      'Pants',
      'Joggers & Sweatpants',
      'Shorts',
      'Kilts',
      'Jumpsuits',
      'Outerwear',
      'Jackets',
      'Vests',
      'Sweaters',
      'Cardigans',
      'Kids & Baby',
      'Boys Clothing',
      'Tops',
      'Graphic Tees',
      'Shorts & Pants',
      'Sweaters',
      'Sweatshirts & Hoodies',
      'Pajamas',
      'Swimwear',
      'Outerwear Jackets',
      'Vests',
      'Girls Clothing',
      'Tops',
      'Graphic Tees',
      'Shorts & Pants',
      'Dresses & Skirts',
      'Sweaters',
      'Sweatshirts & Hoodies',
      'Pajamas',
      'Swimwear',
      'Outerwear Jackets',
      'Vests',
      'Baby Clothing',
      'Body Suits',
      'Graphic Tees & Body Suits',
      'Clothing Sets',
      'Bloomers & Diaper Covers',
      'Pajamas',
      'Newborn Outfits',
      'Baby Buntings',
      'Coming Home',
      'Baby Accessories',
      'Newborn Props',
      'Baby Hats & Bonnets',
      'Leg Warmers',
      'Booties',
      'Kids Accessories',
      'Kids Hats',
      'Kids Gloves & Mittens',
      'Kids Bags',
      'Bags & Purses',
      'Market Bags & Totes',
      'Pouches & Coin Purses',
      'Wallets & Money Clips',
      'Shoulder',
      'Crossbody & Messenger',
      'Belt Bags & Fanny Packs',
      'Sling Bags',
      'Hobo',
      'Wristlets',
      'Clutch & Evening Bags',
      'Bag Inserts & Straps',
      'Backpacks',
      'Diaper Bags',
      'Duffle & Overnight Bags',
      'Cosmetic & Toiletry Bags',
      'Project Bags',
      'Bag Accessories',
      'Luggage & Travel',
      'Luggage Covers',
      'Luggage Straps',
      'Luggage Tags',
      'Passport Covers',
      'Travel Wallets',
      'Hats',
      'Winter Hats',
      'Formal Hats',
      'Sun Hats & Visors',
      'Bucket Hats',
      'Cowboy Hats',
      'Slouchy Hats',
      'Baseball & Trucker Hats',
      'Fedoras',
      'Berets',
      'Fascinators & Mini Hats',
      'Hat Accessories',
      'Earmuffs & Ear Warmers',
      'Scarves & Wraps',
      'Scarves',
      'Wraps & Shawls',
      'Bandanas',
      'Gloves & Mittens',
      'Mittens',
      'Winter Gloves',
      'Arm Warmers',
      'Evening & Formal Gloves',
      'Fingerless Gloves',
      'Hair Accessories',
      'Headbands & Turbans',
      'Barrettes & Clips',
      'Elastics & Ties',
      'Wreaths & Tiaras',
      'Hair Pins',
      'Hair Bows',
      'Scrunchies & Hair Ties',
      'Headband & Bow Holders',
      'Eyewear & Accessories',
      'Sunglasses',
      'Eyeglasses',
      'Eyeglass Chains',
      'Eyewear Storage',
      'Eyeglass Stands',
      'Eyeglass Pouches & Cases',
      'Contact Lens Cases',
      'Eyeglass Cleaning Cloths',
      'Keychains & Lanyards',
      'Keychains',
      'Lanyards',
      'Key Fobs',
      'Badge Holders & Reels',
      'Footwear',
      "Men's Shoes",
      "Women's Shoes",
      'Kids Shoes',
      'Baby Shoes',
      'Socks & Slippers',
      'Adult Socks',
      'Kids Socks',
      'Baby Socks',
      'Adult Slippers',
      'Kids Slippers',
      'Clothing Accessories',
      'Patches & Pins',
      'Patches',
      'Pinback Buttons',
      'Belts & Sashes',
      'Belts',
      'Belt Buckles',
      'Sashes',
      'Ties & Accessories',
      'Neckties',
      'Bowties',
      'Clipon Ties',
      'Legwarmers',
    ],
  },
  {
    main: 'Fine Art & Collectibles',
    subcategories: [
      'Paintings',
      'Acrylic',
      'Gouache',
      'Ink',
      'Oil',
      'Spray Paint',
      'Watercolor',
      'Combination Painting',
      'Fluid Art',
      'Drawing & Illustration',
      'Digital Drawings',
      'Marker Drawings',
      'Pastel or Charcoal Drawings',
      'Pen & Ink Drawings',
      'Pencil Drawings',
      'Architectural Drawings',
      'Custom Portraits',
      'Family Portraits',
      'Pet Portraits',
      'Caricatures',
      'Art Prints',
      'Digital Art Prints',
      'Giclée Prints',
      'Letterpress Prints',
      'Screenprints',
      'Wood & Linocut Prints',
      'Etchings & Engravings',
      'Lithograph & Monotypes',
      'Sculpture',
      'Photography',
      'Fiber & Textile Arts',
      'Art Rugs',
      'Macrame',
      'Weavings',
      'Art Quilts',
      'Tatting & Lace',
      'Felting',
      'Embroidery',
      'Glass Art',
      'Glass Panels & Wall Hangings',
      'Glass Sculpture',
      'Fused Glass',
      'Glass Mosaics',
      'Stained Glass',
      'Mixed Media & Collage',
      'Mosaics',
      'Mixed Media Art',
      'Collage',
      'Metal Art',
      'Paper Art',
      'Quilling',
      'Layered Art',
      'Ceramics',
      'Collectibles',
      'Artist Trading Cards',
      'Art Objects',
      'Sports Collectibles',
      'Militaria',
      'Dolls & Miniatures',
      'Figurines',
      'Miniatures',
      'Dollhouse Miniatures',
      'Dollhouse',
      'Collectible Dolls',
    ],
  },
  {
    main: 'Fun & Games',
    subcategories: [
      'Baby & Toddler Toys',
      'Crib Toys',
      'Blocks & Nesting Toys',
      'Push Toys',
      'Rattles',
      'Big Kid Toys',
      'Ride On Toys',
      'Yoyos & Tops',
      'Kaleidoscopes',
      'Push & Pull Toys',
      'Building Toys',
      'Toy Vehicles',
      'Games & Puzzles',
      'Board Games',
      'Card Games',
      'Dice & Tile Games',
      'Travel Games',
      'Game Pieces',
      'Puzzles',
      'Kids Puzzles',
      'Adult Puzzles',
      'Stuffed Animals, Dolls & Plush',
      'Animals',
      'Amigurumi',
      'Plush',
      'Doll Clothes',
      'Reborn dolls',
      'Sensory Toys',
      'Slime, Foam & Dough',
      'Fidget Toys',
      'Desk Toys',
      'Stress Balls',
      'Kits',
      'Arts & Crafts Fun',
      'Sensory Kits',
      'Pretend Play Kits',
      'Sewing Kits',
      'STEM Kits',
      'Learning',
      'Pretend Play',
      'Play Tents & Forts',
      'Pretend Food',
      'Puppets',
      'Finger Puppets',
      'Hand Puppets',
      'Marionettes',
      'Shadow Puppets',
      'Dress Up',
      'Gag Gifts',
      'Books',
      'Journals',
      'Book Accessories',
      'Bookmarks',
      'Book Covers',
      'Book Stands',
      'Coloring Books',
      'Activity Books',
      'Reference Books & Guides',
      'Comics & Graphic Novels',
      'Cookbooks',
      "Children's Books",
      'Poetry Books',
      'Literature',
      'Costumes & Accessories',
      'Cosplay',
      'Kids Costumes',
      'Costume Accessories',
      'Props',
      'Sports & Outdoor',
      'Lawn Games',
      'Camping & Hiking',
      'Boating & Fishing',
      'Team Sports',
      'Fitness & Exercise',
      'Skateboarding',
      'Shooting & Archery',
      'Holsters',
      'Cycling',
      'Golf',
      'Uniforms',
      'Music',
      'Gig Bags & Instrument Cases',
      'Music Sleeves & Cases',
      'Instrument Straps',
      'Picks & Slides',
      'Music Accessories',
      'Musical Instruments',
      'Drums & Percussion',
      'Stringed Instruments',
      'Woodwinds',
      'Brass Instruments',
      'Keyboard & Piano',
      'Toy Instruments',
    ],
  },
  {
    main: 'Wedding & Celebrations',
    subcategories: [
      'Invitations & Paper',
      'Invitations & Announcements',
      'Invitations',
      'Invitation Kits',
      'Save the Dates',
      'Shower Invites',
      'Announcement Cards',
      'Printable Invitations',
      'Blank Cards & Envelopes',
      'Writing Paper',
      'Labels & Tags',
      'Stamps & Seals',
      'Recipe Cards',
      'Decorative Tape',
      'Gift Wrap',
      'Wrapping Paper',
      'Gift Bags',
      'Gift Boxes',
      'Ribbon & Bows',
      'Gift Tags',
      'Tissue Paper',
      'Party Supplies',
      'Party Decor',
      'Garlands & Bunting',
      'Party Lanterns',
      'Banners',
      'Baking Accessories',
      'Beverage Accessories',
      'Drink Picks',
      'Drink Stirrers',
      'Cocktail Toppers',
      'Party Favors',
      'Favor Bags',
      'Party Games',
      'Cake Toppers',
      'Confetti',
      'Party Hats & Crowns',
      'Piñatas',
      'Photo Props',
      'Backdrops',
      'Photo Booth Props',
      'Photo Signs',
      'Greeting Cards',
      'Thank You Cards',
      'Birthday Cards',
      'Get Well Cards',
      'Love & Wedding Cards',
      'Engagement Cards',
      'Anniversary Cards',
      'New Baby Cards',
      'Sympathy Cards',
      'Good Luck Cards',
      'Moving Cards',
      'Sorry Cards',
      'Thinking of You Cards',
      'Congratulations Cards',
      'Friendship & Encouragement Cards',
      'Miss You Cards',
      'Just Because Cards',
      'Holiday & Seasonal Cards',
      'Valentines Cards',
      'St. Patrick’s Day Cards',
      'Easter Cards',
      'Passover Cards',
      'Patriotic Cards',
      'Thanksgiving Cards',
      'Rosh Hashanah Cards',
      'Christmas Cards',
      'Hanukkah Cards',
      'Diwali Cards',
      'Graduation & School Cards',
      'Religious Events Cards',
      'Bar & Bat Mitzvah',
      'Christenings & Baptisms',
      'First Communion',
      'Confirmation',
      'Wedding Decorations',
      'Centerpieces',
      'Wedding Signs',
      'Wedding Cake Toppers',
      'Ceremony Decor',
      'Guest Books',
      'Wedding Gifts',
      'Bridesmaid & Groomsmen Gifts',
      'Wedding Favors',
      'Dress Hangers',
      'Wedding Albums',
      'Wedding Accessories & Jewelry',
      'Bouquets & Corsages',
      'Wedding Hair Accessories',
      'Boleros & Shrugs',
      'Shawls & Wraps',
      'Belts & Sashes',
      'Veils',
      'Neckties',
      'Wedding Attire',
      'Bridal Gowns & Dresses',
      'Lingerie & Garters',
      'Suits',
      'Flower Girl',
      'Wedding Games',
      'Graduation',
      'Birthday',
      'Adult Birthday',
      'Children’s Birthday',
      'Age Specific Birthday',
      'First Birthday',
      'Sweet 16',
      'Quinceañera',
      'Over the Hill',
      'Religious Celebrations',
      'Baby Showers',
    ],
  },
  {
    main: 'Handmade Supplies',
    subcategories: [
      'Sewing & Fiber Supplies',
      'Patterns',
      'Cross Stitch Patterns',
      'Embroidery Patterns',
      'Knitting Patterns',
      'Crochet Patterns',
      'Sewing Patterns',
      'Quilting Patterns',
      'Sewing Tools & Supplies',
      'Fiber Art Tools',
      'Yarn',
      'Embroidery & Needlework Supplies',
      'Embroidery Design Files',
      'Wool & Felting',
      'Macrame Supplies',
      'Leatherworking Supplies',
      'Fabric',
      'Quilting Supplies',
      'Notions & Embellishments',
      'Pom-Poms',
      'Tassels',
      'Appliques',
      'Patches',
      'Ribbon',
      'Jewelry & Beauty Supplies',
      'Jewelry Findings',
      'Beading Supplies',
      'Cabochons',
      'Rocks & Gemstones',
      'Hair Crafts',
      'Soap Making',
      'Paint & Stains',
      'Watercolor Paints',
      'Art Paint',
      'Chalk Paint',
      'Ink',
      'Dye & Pigments',
      'Stains',
      'Paint Palettes',
      'Color Palettes',
      'Digital Files & Templates',
      'Design Patterns & Templates',
      'SVG & Image Files',
      'Fonts',
      'Templates & Guides',
      'Laser Files',
      '3D Printer Files',
      'Product Mockup',
      'Transfers',
      'Sublimation Transfers',
      'Iron On Transfers',
      'Rub On Transfers',
      'Vinyl Transfers',
      'Papercraft',
      'Digital Paper',
      'Paper Craft Kits',
      'Scrapbook & Journaling Supplies',
      'Handmade Paper',
      'Die Cuts',
      'Handmade Papers',
      'Sculpting & Forming',
      'Jigs',
      'Molds',
      'Cutters',
      'Stencils',
      'Pottery & Ceramic Supplies',
      'Woodworking Supplies',
      'Candle Making',
      'Tool Belts & Utility Aprons',
      'Blanks',
      'Forms & Shapes',
      'Jewelry Blanks',
      'Stamping Blanks',
      'Home & Hobby',
      'Cake Decorating Supplies',
      'Fondant',
      'Edible Decorations',
      'Candy Embellishments',
      'Edible Cake Toppers',
      'Small Business Supplies',
      'Business Cards',
      'Package Inserts',
      'Custom Stickers',
      'Custom Banners',
      'Packaging',
      'Custom Stamps',
      'Goimagine Street Team',
      'Creative Services',
      'Longarm Quilting Services',
      'Graphic Design Services',
    ],
  },
  {
    main: 'Tools & Equipment',
    subcategories: [
      'Hand Tools',
      'Screwdrivers',
      'Wrenches',
      'Socket Sets',
      'Ratchets',
      'Hammers',
      'Mallets',
      'Pliers',
      'Cutters',
      'Saws',
      'Chisels',
      'Files & Rasps',
      'Hex & Torx Keys',
      'Utility Knives',
      'Pry Bars',
      'Clamps & Vices',
      'Measuring & Layout Tools',
      'Tape Measures',
      'Laser Distance Meters',
      'Spirit Levels',
      'Laser Levels',
      'Squares',
      'Calipers',
      'Micrometers',
      'Angle Finders',
      'Marking Gauges',
      'Power Tools',
      'Drills & Drivers',
      'Hammer Drills',
      'Impact Wrenches',
      'Rotary Hammers',
      'Circular Saws',
      'Miter Saws',
      'Table Saws',
      'Jigsaws',
      'Reciprocating Saws',
      'Angle Grinders',
      'Die Grinders',
      'Sanders & Polishers',
      'Planers',
      'Routers',
      'Nail Guns & Staplers',
      'Heat Guns',
      'Multi-Tools',
      'Air Tools & Compressors',
      'Air Compressors',
      'Air Impact Tools',
      'Air Sanders',
      'Air Nailers',
      'Spray Guns',
      'Workshop & Garage Equipment',
      'Workbenches',
      'Tool Chests',
      'Tool Cabinets',
      'Tool Bags',
      'Shelving & Storage',
      'Hydraulic Jacks',
      'Engine Hoists',
      'Bench Grinders',
      'Drill Presses',
      'Band Saws',
      'Welding Equipment',
      'Welders',
      'Plasma Cutters',
      'Welding Helmets',
      'Welding Accessories',
      'Electrical Tools',
      'Multimeters',
      'Cable Testers',
      'Wire Strippers',
      'Crimpers',
      'Soldering Tools',
      'Conduit Tools',
      'Plumbing Tools',
      'Pipe Wrenches',
      'Pipe Cutters',
      'Threading Tools',
      'Drain Tools',
      'Pressure Test Tools',
      'Construction Equipment',
      'Scaffolding',
      'Ladders',
      'Concrete Mixers',
      'Compactors',
      'Plate Compactors',
      'Jackhammers',
      'Core Drills',
      'Tile Cutters',
      'Drywall Tools',
      'Demolition Tools',
      'Material Lifts',
      'Generators',
      'Water Pumps',
      'Lighting Towers',
      'Site Safety Barriers',
      'Landscaping Equipment',
      'Chainsaws',
      'Brush Cutters',
      'Leaf Blowers',
      'Hedge Trimmers',
      'Pressure Washers',
      'Mini Excavators',
      'Skid Steers',
      'Safety Gear',
      'Hard Hats',
      'Safety Glasses',
      'Hearing Protection',
      'Respirators',
      'Work Gloves',
      'Hi-Vis Clothing',
      'Fall Protection',
    ],
  },
  {
    main: 'Holiday & Seasonal',
    subcategories: [
      'Valentine’s Day',
      'St. Patricks Day',
      'Spring & Easter',
      'Mother’s Day',
      'Father’s Day',
      'Summer & 4th of July',
      'Back to School',
      'Fall & Thanksgiving',
      'Halloween',
      'Christmas',
      'Kwanzaa',
      'Hanukkah',
      'Diwali',
      'New Year’s Eve',
    ],
  },
]

export const marketplaceCategoryLabels = goimagineCategories.map((category) => category.main)

export function getMarketplaceSubcategories(mainCategory: MarketplaceMainCategory) {
  return goimagineCategories.find((category) => category.main === mainCategory)?.subcategories || []
}
